[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"  # Corrected 'functions' to 'directory' to match Netlify's expected config

[dev]
  framework = "next"
  port = 8888
  autoLaunch = false
