[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/netlify-api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[dev]
  framework = "next"
  port = 8888
  autoLaunch = false
