[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/:function"
  to = "/.netlify/functions/:function"
  status = 200
  force = true


[functions]
  directory = "netlify/functions"